/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Asset1 {
  /** The name of the asset. */
  name?: string;
  /** The symbol of the asset. */
  symbol?: string;
  /** The id of the asset. */
  id?: number;
}

export const asset1Schema: Schema<Asset1> = object({
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  id: ['id', optional(number())],
});
