/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface Asset {
  id?: number;
  name?: string;
  symbol?: string;
  contracts?: string[];
  blockchains?: string[];
  twitter?: string;
  website?: string;
  logo?: string;
  price?: number;
  marketCap?: number;
  liquidity?: number;
  volume?: number;
  description?: string;
  kyc?: string;
  audit?: string;
  totalSupplyContracts?: string[];
  totalSupply?: number;
  circulatingSupply?: number;
  circulatingSupplyAddresses?: string[];
  discord?: string;
}

export const assetSchema: Schema<Asset> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  contracts: ['contracts', optional(array(string()))],
  blockchains: ['blockchains', optional(array(string()))],
  twitter: ['twitter', optional(string())],
  website: ['website', optional(string())],
  logo: ['logo', optional(string())],
  price: ['price', optional(number())],
  marketCap: ['market_cap', optional(number())],
  liquidity: ['liquidity', optional(number())],
  volume: ['volume', optional(number())],
  description: ['description', optional(string())],
  kyc: ['kyc', optional(string())],
  audit: ['audit', optional(string())],
  totalSupplyContracts: ['total_supply_contracts', optional(array(string()))],
  totalSupply: ['total_supply', optional(number())],
  circulatingSupply: ['circulating_supply', optional(number())],
  circulatingSupplyAddresses: [
    'circulating_supply_addresses',
    optional(array(string())),
  ],
  discord: ['discord', optional(string())],
});
