/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema } from '../schema';
import { Asset1, asset1Schema } from './asset1';

export interface Asset2 {
  asset?: Asset1;
  /** The ROI of the asset. */
  roi?: number;
  /** The share of the user’s portfolio dedicated to this asset. */
  allocation?: number;
  /** The USD balance of the asset held by the user. */
  estimatedBalance?: number;
  /** The current price of the asset. */
  price?: number;
  /** The average bought price of the asset by the user. */
  priceBought?: number;
  /** The balance of the asset. */
  balance?: number;
}

export const asset2Schema: Schema<Asset2> = object({
  asset: ['asset', optional(lazy(() => asset1Schema))],
  roi: ['roi', optional(number())],
  allocation: ['allocation', optional(number())],
  estimatedBalance: ['estimated_balance', optional(number())],
  price: ['price', optional(number())],
  priceBought: ['price_bought', optional(number())],
  balance: ['balance', optional(number())],
});
