/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface CryptoData {
  /** The unique identifier of the cryptocurrency */
  id?: number;
  /** The name of the cryptocurrency */
  name?: string;
  /** The symbol of the cryptocurrency */
  symbol?: string;
  /** The blockchains on which the cryptocurrency exists */
  blockchains?: string[];
}

export const cryptoDataSchema: Schema<CryptoData> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  blockchains: ['blockchains', optional(array(string()))],
});
