/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface MarketDataResponse {
  /** The market cap of the asset. */
  marketCap?: number;
  /** The liquidity of the asset. */
  liquidity?: number;
  /** The price of the asset. */
  price?: number;
}

export const marketDataResponseSchema: Schema<MarketDataResponse> = object({
  marketCap: ['market_cap', optional(number())],
  liquidity: ['liquidity', optional(number())],
  price: ['price', optional(number())],
});
