/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface SearchCryptoData {
  /** The unique identifier of the cryptocurrency */
  id?: number;
  /** The name of the cryptocurrency */
  name?: string;
  /** The symbol of the cryptocurrency */
  symbol?: string;
  /** The contracts associated with the cryptocurrency */
  contracts?: string[];
  /** The blockchains on which the cryptocurrency exists */
  blockchains?: string[];
  /** The Twitter link of the cryptocurrency */
  twitter?: string;
  /** The website of the cryptocurrency */
  website?: string;
  /** The logo of the cryptocurrency */
  logo?: string;
  /** The price of the cryptocurrency */
  price?: number;
  /** The market cap of the cryptocurrency */
  marketCap?: bigint;
  /** The liquidity of the cryptocurrency */
  liquidity?: bigint;
  /** The volume of the cryptocurrency */
  volume?: bigint;
}

export const searchCryptoDataSchema: Schema<SearchCryptoData> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  symbol: ['symbol', optional(string())],
  contracts: ['contracts', optional(array(string()))],
  blockchains: ['blockchains', optional(array(string()))],
  twitter: ['twitter', optional(string())],
  website: ['website', optional(string())],
  logo: ['logo', optional(string())],
  price: ['price', optional(number())],
  marketCap: ['market_cap', optional(bigint())],
  liquidity: ['liquidity', optional(bigint())],
  volume: ['volume', optional(bigint())],
});
