/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Asset2, asset2Schema } from './asset2';

export interface WalletPortfolioResponse {
  assets?: Asset2[];
}

export const walletPortfolioResponseSchema: Schema<WalletPortfolioResponse> = object(
  { assets: ['assets', optional(array(lazy(() => asset2Schema)))] }
);
